Feature/Implement getTransaction for crypto transfer
hashgraph/hethers.js pull request #159
Opened 2022-02-11 10:22 UTC by natanasow

**Description**:

**Related issue(s)**:

Fixes #
- https://github.com/hashgraph/hethers.js/issues/156

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-02-11 12:31 UTC, natanasow commented on packages/tests/src.ts/test-wallet.spec.ts
> +            value: 1.8925
hbar

2022-02-11 12:55 UTC, Daniel-K-Ivanov requested changes

2022-02-11 12:55 UTC, Daniel-K-Ivanov commented on packages/providers/src.ts/base-provider.ts
> +                        record.amount = toTransfers.reduce((a: any, b: any) => a + b.amount, 0);
Use Custom data for multiple transfers

2022-02-14 08:11 UTC, joan41868 commented on packages/abstract-provider/src.ts/index.ts
> +    transfersList?: Array<{ to: string, amount: number }>
I think that this transfer list will work **only** for `Hbar` transfers.
Will we ever support HTS (hedera token service) tokens?

2022-02-14 08:20 UTC, joan41868 commented on packages/abstract-provider/src.ts/index.ts
> +    transfersList?: Array<{ to: string, amount: number }>
We won't support `HTS` tokens. You can resolve this.

2022-02-14 14:39 UTC, Daniel-K-Ivanov approved these changes

2022-02-14 16:04 UTC, merged