Support for contract aliases
hashgraph/hethers.js pull request #209
Opened 2022-03-10 10:06 UTC by joan41868

Signed-off-by: Yoan Sredkov <yoansredkov@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-03-16 08:56 UTC, Daniel-K-Ivanov requested changes

2022-03-16 08:56 UTC, Daniel-K-Ivanov commented on packages/contracts/src.ts/index.ts
> +    return address.split('').filter(e => e === '0').length < 12;
Wouldn't it be more cleaner if we use:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2022-03-16 08:56 UTC, Daniel-K-Ivanov commented on packages/transactions/src.ts/index.ts
> +        // }
Lets remove the comments

2022-03-16 08:56 UTC, Daniel-K-Ivanov commented on packages/tests/src.ts/test-contract.spec.ts
> +        // const aliasAddress3 = '0x3ff6c75494fb24144F5559D1d9F9072a51D482d6';
Do we need those addresses?

2022-03-16 12:05 UTC, natanasow submitted a review, later dismissed

2022-03-17 09:15 UTC, Daniel-K-Ivanov approved these changes

2022-03-17 09:15 UTC, merged