Use links.next in eth_getLogs
hashgraph/hethers.js pull request #267
Opened 2022-08-09 15:09 UTC by georgi-l95

Signed-off-by: georgi-l95 glazarov95@gmail.com

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-08-10 14:42 UTC, Ivo-Yankov requested changes
Looks good. Could you please add a test for this functionallity?

2022-08-10 18:13 UTC, natanasow requested changes
LG, but we need to add tests. Also, could you clean up the `test-providers.spec.ts` from commented code.

2022-08-15 07:28 UTC, natanasow approved these changes

2022-08-15 08:01 UTC, Ivo-Yankov approved these changes

2022-08-15 08:40 UTC, merged