`HederaProvider` implementation
hashgraph/hethers.js pull request #57
Opened 2021-12-17 13:28 UTC by joan41868

Signed-off-by: Yoan Sredkov <yoansredkov@gmail.com>

**Description**:

This **PR** adds `HederaProvider` class, which can be used to connect to a custom network.
Modifies the `BaseProvider` class in order to support the custom network from the hedera sdk's `Client`.

**Related issue(s)**:

Fixes #11 

**Notes for reviewer**:
There is an example with the local network. Please do double check for the node urls on your PC.
**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-05 14:04 UTC, Daniel-K-Ivanov requested changes

2022-01-07 07:25 UTC, joan41868 commented on packages/providers/src.ts/base-provider.ts
> +    protected mirrorNodeUrl: string; // overridable mirror node URL
One possible solution is to modify the `_mirrorNodeUrl` in order to be overridable, e.g. it has to be `protected`. Private members cannot be mofidied from their super classes

2022-01-07 07:27 UTC, joan41868 commented on examples/provider.example.ts
> +    const provider2 = new hethers.providers.HederaProvider(genesis.network["127.0.0.1:50211"], "127.0.0.1:50211", "");
The `getBalance` operation won't crash, as it uses the `@hashgraph/sdk` to query for the balance.
`getTransaction` will definetely crash as there is no local mirror node for now.

I'll rework the example to use `testnet` urls.

2022-01-07 07:28 UTC, joan41868 commented on examples/provider.example.ts
>      const provider = hethers.providers.getDefaultProvider("testnet");
Will fix this later as the changes you suggested are actually present on other branches.

2022-01-14 09:31 UTC, Daniel-K-Ivanov submitted a review, later dismissed

2022-01-17 06:39 UTC, Daniel-K-Ivanov approved these changes

2022-01-17 06:39 UTC, merged