Base provider cleanup
hashgraph/hethers.js pull request #67
Opened 2022-01-09 16:26 UTC by joan41868

Signed-off-by: Yoan Sredkov <yoansredkov@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-10 12:01 UTC, Daniel-K-Ivanov requested changes
Good progress towards cleaning the provider classes!

2022-01-10 12:01 UTC, Daniel-K-Ivanov commented on packages/tests/src.ts/test-providers.spec.ts
> +// describe("Test Provider Methods", function() {
We can remove the commented tests here and add `TODOs` for adding tests for the provider methods once we implement them

2022-01-11 09:04 UTC, joan41868 commented on packages/providers/src.ts/base-provider.ts
> -}
I will leave events and the serdes for now, as I found usage in the `contracts` package.

2022-01-12 15:55 UTC, Daniel-K-Ivanov requested changes

2022-01-12 15:55 UTC, Daniel-K-Ivanov commented on packages/providers/src.ts/base-provider.ts
> +    async poll(): Promise<void> {}
Do we need to keep this function? I think that we do not need it

2022-01-12 15:55 UTC, Daniel-K-Ivanov commented on packages/providers/src.ts/base-provider.ts
>      resetEventsBlock(blockNumber: number): void {
Can't we delete this function. It seems that we wont need it

2022-01-12 15:55 UTC, Daniel-K-Ivanov commented on packages/providers/src.ts/base-provider.ts
>      async estimateGas(transaction: Deferrable<TransactionRequest>): Promise<BigNumber> {
Instead of returning `0`, lets throw not implemented/not supported

2022-01-12 16:02 UTC, Daniel-K-Ivanov approved these changes
Lets wait for CICD to go through and we can merge

2022-01-13 07:49 UTC, merged